require 'sprout'
sprout 'as3'

# jerryvos-sprouts-extensions gem
require 'sprouts-extensions'

require 'rake_helpers/config'
MP::Config.global_settings_file = 'rake_config.yml' if File.exist?('rake_config.yml')

Dir["#{File.dirname(__FILE__)}/tasks/**/*.rake"].sort.each { |ext| load ext }
Dir["#{File.dirname(__FILE__)}/build/**/*.rake"].sort.each { |ext| load ext }

flexspec_config.repo_location = File.expand_path('../.git')

test_config.app_name = 'Flexspec'
test_config.test_dir = "src"
test_config.test_suite_dir = 'src'